version: '3.7'
services:
    socket:
      build:
        context: .
        dockerfile: Dockerfile_socket
      container_name: socket
      volumes:
        - ./socket:/app
      ports:
        - 3001:3001
    mongo:
      container_name: mongo
      image: mongo

      volumes:
        - mongoData:/data/db
    mongo-express:
      container_name: mongo_express
      image: mongo-express
      depends_on:
        - mongo
      ports:
        - 8082:8081
      environment:
        ME_CONFIG_MONGODB_URL: mongodb://lol:example@mongo:27017/
        ME_CONFIG_MONGODB_SERVER: mongo
        ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
    node_express:
      container_name: express
      ports:
        - 3000:3000
      build:
        context: .
        dockerfile: Dockerfile_node
      depends_on:
        - mongo
      volumes:
        - ./back:/app
    vue:
      container_name: vue
      depends_on:
        - node_express
      build:
        context: .
        dockerfile: Dockerfile_vue
      volumes:
        - ./vuethirdtry:/app
      ports:
        - 80:8080
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: lol
        ME_CONFIG_MONGODB_ADMINPASSWORD: noquiero
        ME_CONFIG_MONGODB_URL: mongodb://lol:example@mongo:27017/
volumes:
    .:
    mongoData:
