version: '3.7'
services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes: 
            - ./source:/app
        ports:
            - 9000:8080
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_DATABASE: lol
            MYSQL_USER: lol
            MYSQL_PASSWORD: noquiero
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - 33069:3306
        volumes:
            - ./datos:/var/lib/mysql
        depends_on:
            - php
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - 8000:8080
        volumes:
            - ./source:/app
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
    phpMyAdmin:
        image: phpmyadmin:latest
        container_name: phpMyAdmin
        environment:
            MYSQL_ROOT_PASSWORD: admin
        depends_on:
            - mysql
        ports:
            - 8080:80
    
volumes: 
    .:
