version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app
        networks:
            - code
    php:
        image: php:fpm
        volumes:
            - ./app:/app
        networks:
            - code
networks:
    code:
        driver: bridge
volumes: 
    .: