version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:alpine
    environment:
      POSTGRES_USER: lol
      POSTGRES_PASSWORD: something
      PGDATA: /data/postgres
      POSTGRES_DB: wichos
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: bonillaandres95@gmail.com
      PGADMIN_DEFAULT_PASSWORD: something
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/root/.pgadmin
    depends_on: 
       - postgres

    ports:
      - "5050:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
